[project]
name = "odoo-addons-oca-ai"
version = "18.0.20250918.0"
dependencies = [
    "odoo-addon-ai_oca_bridge==1.*",
    "odoo-addon-ai_oca_bridge_document_page==1.*",
    "odoo-addon-ai_oca_native_generate_ollama==1.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
